export const countries = [
  { name: "India", dial_code: "+91", code: "IN", length: 10 },
  { name: "United States", dial_code: "+1", code: "US", length: 10 },
  { name: "United Kingdom", dial_code: "+44", code: "GB", length: 10 },
  { name: "Canada", dial_code: "+1", code: "CA", length: 10 },
  { name: "Australia", dial_code: "+61", code: "AU", length: 9 },
  { name: "Germany", dial_code: "+49", code: "DE", length: 11 },
  { name: "France", dial_code: "+33", code: "FR", length: 9 },
  { name: "Japan", dial_code: "+81", code: "JP", length: 10 },
  { name: "China", dial_code: "+86", code: "CN", length: 11 },
  { name: "Brazil", dial_code: "+55", code: "BR", length: 11 },
  { name: "Russia", dial_code: "+7", code: "RU", length: 10 },
  { name: "Italy", dial_code: "+39", code: "IT", length: 10 },
  { name: "Spain", dial_code: "+34", code: "ES", length: 9 },
  { name: "Mexico", dial_code: "+52", code: "MX", length: 10 },
  { name: "South Korea", dial_code: "+82", code: "KR", length: 10 },
  { name: "Indonesia", dial_code: "+62", code: "ID", length: 11 },
  { name: "Turkey", dial_code: "+90", code: "TR", length: 10 },
  { name: "Saudi Arabia", dial_code: "+966", code: "SA", length: 9 },
  { name: "United Arab Emirates", dial_code: "+971", code: "AE", length: 9 },
  { name: "South Africa", dial_code: "+27", code: "ZA", length: 9 },
  { name: "Argentina", dial_code: "+54", code: "AR", length: 10 },
  { name: "Netherlands", dial_code: "+31", code: "NL", length: 9 },
  { name: "Sweden", dial_code: "+46", code: "SE", length: 9 },
  { name: "Switzerland", dial_code: "+41", code: "CH", length: 9 },
  { name: "Belgium", dial_code: "+32", code: "BE", length: 9 },
  { name: "Singapore", dial_code: "+65", code: "SG", length: 8 },
  { name: "New Zealand", dial_code: "+64", code: "NZ", length: 9 },
  { name: "Ireland", dial_code: "+353", code: "IE", length: 9 },
  { name: "Norway", dial_code: "+47", code: "NO", length: 8 },
  { name: "Denmark", dial_code: "+45", code: "DK", length: 8 },
  { name: "Finland", dial_code: "+358", code: "FI", length: 9 },
  { name: "Portugal", dial_code: "+351", code: "PT", length: 9 },
  { name: "Poland", dial_code: "+48", code: "PL", length: 9 },
  { name: "Greece", dial_code: "+30", code: "GR", length: 10 },
  { name: "Pakistan", dial_code: "+92", code: "PK", length: 10 },
  { name: "Bangladesh", dial_code: "+880", code: "BD", length: 10 },
  { name: "Vietnam", dial_code: "+84", code: "VN", length: 9 },
  { name: "Philippines", dial_code: "+63", code: "PH", length: 10 },
  { name: "Thailand", dial_code: "+66", code: "TH", length: 9 },
  { name: "Malaysia", dial_code: "+60", code: "MY", length: 9 },
  { name: "Egypt", dial_code: "+20", code: "EG", length: 10 },
  { name: "Israel", dial_code: "+972", code: "IL", length: 9 },
];
