import type { Tester } from './types';

export const testers: Tester[] = [
  {
    id: 1,
    name: 'Alice Johnson',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'woman developer',
    skills: ['UI/UX', 'Mobile', 'Web'],
    reputation: 4.9,
    rate: 75,
    country: 'USA',
  },
  {
    id: 2,
    name: 'Bob Williams',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'man glasses',
    skills: ['Security', 'API', 'Performance'],
    reputation: 4.8,
    rate: 90,
    country: 'Canada',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'man smiling',
    skills: ['Game Testing', 'VR/AR', 'Mobile'],
    reputation: 4.9,
    rate: 80,
    country: 'UK',
  },
  {
    id: 4,
    name: 'Diana Miller',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'woman smiling',
    skills: ['Web', 'Accessibility', 'UI/UX'],
    reputation: 4.7,
    rate: 65,
    country: 'Australia',
  },
  {
    id: 5,
    name: 'Ethan Garcia',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'man engineer',
    skills: ['Performance', 'Backend', 'API'],
    reputation: 4.8,
    rate: 95,
    country: 'Germany',
  },
  {
    id: 6,
    name: 'Fiona Clark',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'woman glasses',
    skills: ['Mobile', 'iOS', 'Android'],
    reputation: 4.9,
    rate: 85,
    country: 'France',
  },
  {
    id: 7,
    name: 'George Hill',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'man portrait',
    skills: ['Security', 'Penetration Testing'],
    reputation: 5.0,
    rate: 120,
    country: 'USA',
  },
  {
    id: 8,
    name: 'Hannah Wright',
    avatarUrl: 'https://placehold.co/128x128/png',
    dataAiHint: 'woman tech',
    skills: ['UI/UX', 'Figma', 'Web'],
    reputation: 4.8,
    rate: 70,
    country: 'UK',
  },
];

export const chartData = [
    { month: 'January', reports: 186, resolved: 80 },
    { month: 'February', reports: 305, resolved: 200 },
    { month: 'March', reports: 237, resolved: 120 },
    { month: 'April', reports: 273, resolved: 190 },
    { month: 'May', reports: 209, resolved: 130 },
    { month: 'June', reports: 214, resolved: 140 },
];

export const pieChartData = [
    { category: 'UI/UX', bugs: 275, fill: 'var(--color-ui)' },
    { category: 'Functional', bugs: 200, fill: 'var(--color-functional)' },
    { category: 'Performance', bugs: 187, fill: 'var(--color-performance)' },
    { category: 'Security', bugs: 125, fill: 'var(--color-security)' },
    { category: 'Other', bugs: 73, fill: 'var(--color-other)' },
];
