import type { AutoGeneratedStats } from "@/lib/types";

export function getDefaultAnswer(key: string, stats?: AutoGeneratedStats): string {
  if (!stats) return "";

  const {
    totalTesters = 0,
    completedTesters = 0,
    totalDays = 0,
    bugs = 0,
    suggestions = 0,
    praise = 0,
    totalFeedback = 0,
    avgRating = null,
    category = "",
  } = stats;

  const pct = totalTesters > 0 ? Math.round((completedTesters / totalTesters) * 100) : 0;
  const engagementLevel = pct >= 70 ? "strong" : pct >= 40 ? "moderate" : "limited";
  const projectedInstalls = Math.max(completedTesters * 10, 100);
  const ratingText = avgRating !== null ? `${avgRating}/5` : "positive";

  const defaults: Record<string, string> = {
    recruitmentMethod:
      "Testers were recruited through the inTesters platform, a community-driven marketplace that connects developers with certified beta testers via reward-based participation.",
    recruitmentEase:
      `The app attracted ${totalTesters} testers, with ${completedTesters} (${pct}%) completing the full ${totalDays}-day test cycle, indicating ${engagementLevel} community interest and manageable onboarding.`,
    testerEngagement:
      `Testers submitted ${totalFeedback} feedback items over ${totalDays} days, including ${praise} praise notes, ${suggestions} suggestions, and ${bugs} bug reports. Most testers actively engaged in daily verification tasks and provided actionable insights.`,
    feedbackSummary:
      `Positive feedback (${praise} items) highlighted intuitive UX and smooth onboarding. Constructive feedback (${suggestions} items) covered feature requests and workflow improvements. Bug reports (${bugs} issues) were documented and addressed during testing.`,
    feedbackCollectionMethod:
      "Feedback was collected through the inTesters platform’s structured system that categorizes input as Bug, Suggestion, Praise, or Other, with optional screenshot or video attachments.",
    intendedAudience:
      `The app targets ${category || "general"} users seeking specialized tools in this domain—including professionals, hobbyists, and everyday users who need reliable software solutions.`,
    valueDescription:
      `This ${category || "application"} provides organized tools and streamlined workflows that help users accomplish tasks efficiently, reduce manual overhead, and improve productivity in their daily routine.`,
    expectedInstalls:
      `Based on tester engagement and community interest during the ${completedTesters}-tester closed beta, a conservative first-year projection is ${projectedInstalls}+ installs, with potential for accelerated growth through platform promotion.`,
    changesMade:
      `During testing, ${bugs} reported bugs were identified and fixed, and ${suggestions} user suggestions were incorporated to improve navigation, stability, and overall user experience based on real-world tester feedback.`,
    readinessRationale:
      `The app completed a rigorous ${totalDays}-day closed beta with ${completedTesters} testers. All critical feedback was addressed through iterative improvements. The average tester rating is ${ratingText}, confirming production readiness.`,
  };

  return defaults[key] || "";
}
