export const mockApplications = [
  {
    id: 1,
    name: "Maria Garcia",
    email: "maria@example.com",
    date: "2024-08-20",
    experience: "3-5 years",
    expertise: ["Manual", "Usability"],
    status: "pending",
  },
  {
    id: 2,
    name: "David Kim",
    email: "david@example.com",
    date: "2024-08-19",
    experience: "5+ years",
    expertise: ["Automation", "Performance", "API"],
    status: "pending",
  },
  {
    id: 3,
    name: "Alex Johnson",
    email: "alex@example.com",
    date: "2024-08-18",
    experience: "1-3 years",
    expertise: ["Manual"],
    status: "approved",
  },
  {
    id: 4,
    name: "Priya Patel",
    email: "priya@example.com",
    date: "2024-08-17",
    experience: "3-5 years",
    expertise: ["Security", "Manual"],
    status: "pending",
  },
  {
    id: 5,
    name: "Michael Chen",
    email: "michael@example.com",
    date: "2024-08-16",
    experience: "5+ years",
    expertise: ["Automation", "API", "Performance"],
    status: "approved",
  },
  {
    id: 6,
    name: "Emily White",
    email: "emily@example.com",
    date: "2024-08-15",
    experience: "1-3 years",
    expertise: ["Usability"],
    status: "rejected",
  },
  {
    id: 7,
    name: "James Brown",
    email: "james@example.com",
    date: "2024-08-14",
    experience: "3-5 years",
    expertise: ["Manual", "API"],
    status: "pending",
  },
  {
    id: 8,
    name: "Olivia Green",
    email: "olivia@example.com",
    date: "2024-08-13",
    experience: "5+ years",
    expertise: ["Automation", "Security"],
    status: "approved",
  },
  {
    id: 9,
    name: "William Black",
    email: "william@example.com",
    date: "2024-08-12",
    experience: "0-1 years",
    expertise: ["Manual"],
    status: "pending",
  },
  {
    id: 10,
    name: "Sophia Grey",
    email: "sophia@example.com",
    date: "2024-08-11",
    experience: "3-5 years",
    expertise: ["Performance", "Usability"],
    status: "rejected",
  },
];
