"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Plus,
  Trash2,
  Save,
  Send,
  Loader2,
  FileText,
  AlertCircle,
  CheckCircle2,
} from "lucide-react";
import { toast } from "@/hooks/use-toast";
import type { DeclarationAnswers, AutoGeneratedStats } from "@/lib/types";
import {
  useAdminDeclaration,
  useUpdateAdminDeclaration,
  usePublishAdminDeclaration,
} from "@/hooks/use-declaration";

interface AdminQuestionItem {
  id: string;
  question: string;
  answer: string;
  createdAt: string;
}

function generateAdminQuestionId(): string {
  return `admin_q_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}

const STANDARD_QUESTIONS: { key: keyof DeclarationAnswers; question: string }[] = [
  { key: "recruitmentMethod", question: "How did you recruit users for your closed test?" },
  { key: "recruitmentEase", question: "How easy was it to recruit testers for your app?" },
  { key: "testerEngagement", question: "Describe the engagement you received from testers during your closed test." },
  { key: "feedbackSummary", question: "Provide a summary of the feedback that you received from testers." },
  { key: "feedbackCollectionMethod", question: "How did you collect the feedback?" },
  { key: "intendedAudience", question: "Who is the intended audience of your app?" },
  { key: "valueDescription", question: "Describe how your app provides value to users." },
  { key: "expectedInstalls", question: "How many installs do you expect your app to have in its first year?" },
  { key: "changesMade", question: "What changes did you make to your app based on what you learned during your closed test?" },
  { key: "readinessRationale", question: "How did you decide that your app is ready for production?" },
];

function getDefaultAnswer(key: string, stats?: AutoGeneratedStats): string {
  if (!stats) return "";

  const {
    totalTesters = 0,
    completedTesters = 0,
    totalDays = 0,
    bugs = 0,
    suggestions = 0,
    praise = 0,
    totalFeedback = 0,
    avgRating = null,
    category = "",
  } = stats;

  const pct = totalTesters > 0 ? Math.round((completedTesters / totalTesters) * 100) : 0;
  const engagementLevel = pct >= 70 ? "strong" : pct >= 40 ? "moderate" : "limited";
  const projectedInstalls = Math.max(completedTesters * 10, 100);
  const ratingText = avgRating !== null ? `${avgRating}/5` : "positive";

  const defaults: Record<string, string> = {
    recruitmentMethod:
      "Testers were recruited through the inTesters platform, a community-driven marketplace that connects developers with certified beta testers via reward-based participation.",
    recruitmentEase:
      `The app attracted ${totalTesters} testers, with ${completedTesters} (${pct}%) completing the full ${totalDays}-day test cycle, indicating ${engagementLevel} community interest and manageable onboarding.`,
    testerEngagement:
      `Testers submitted ${totalFeedback} feedback items over ${totalDays} days, including ${praise} praise notes, ${suggestions} suggestions, and ${bugs} bug reports. Most testers actively engaged in daily verification tasks and provided actionable insights.`,
    feedbackSummary:
      `Positive feedback (${praise} items) highlighted intuitive UX and smooth onboarding. Constructive feedback (${suggestions} items) covered feature requests and workflow improvements. Bug reports (${bugs} issues) were documented and addressed during testing.`,
    feedbackCollectionMethod:
      "Feedback was collected through the inTesters platform\u2019s structured system that categorizes input as Bug, Suggestion, Praise, or Other, with optional screenshot or video attachments.",
    intendedAudience:
      `The app targets ${category || "general"} users seeking specialized tools in this domain\u2014including professionals, hobbyists, and everyday users who need reliable software solutions.`,
    valueDescription:
      `This ${category || "application"} provides organized tools and streamlined workflows that help users accomplish tasks efficiently, reduce manual overhead, and improve productivity in their daily routine.`,
    expectedInstalls:
      `Based on tester engagement and community interest during the ${completedTesters}-tester closed beta, a conservative first-year projection is ${projectedInstalls}+ installs, with potential for accelerated growth through platform promotion.`,
    changesMade:
      `During testing, ${bugs} reported bugs were identified and fixed, and ${suggestions} user suggestions were incorporated to improve navigation, stability, and overall user experience based on real-world tester feedback.`,
    readinessRationale:
      `The app completed a rigorous ${totalDays}-day closed beta with ${completedTesters} testers. All critical feedback was addressed through iterative improvements. The average tester rating is ${ratingText}, confirming production readiness.`,
  };

  return defaults[key] || "";
}

function deriveSeedQuestions(
  answers: DeclarationAnswers,
  stats?: AutoGeneratedStats,
): AdminQuestionItem[] {
  const now = new Date().toISOString();
  const result: AdminQuestionItem[] = [];

  for (const { key, question } of STANDARD_QUESTIONS) {
    const userAnswer = (answers[key] as string) || "";
    const answer = userAnswer.trim() || getDefaultAnswer(key, stats);
    result.push({
      id: generateAdminQuestionId(),
      question,
      answer,
      createdAt: now,
    });
  }

  for (const cq of answers.customQuestions || []) {
    if (cq.question.trim() || cq.answer.trim()) {
      result.push({
        id: generateAdminQuestionId(),
        question: cq.question,
        answer: cq.answer,
        createdAt: now,
      });
    }
  }

  return result;
}

export function AdminDeclarationEditor({ appId }: { appId: number }) {
  const [questions, setQuestions] = useState<AdminQuestionItem[]>([]);
  const [hasUnsaved, setHasUnsaved] = useState(false);

  const {
    data: declaration,
    isPending,
    error,
    refetch,
  } = useAdminDeclaration(appId);

  const { mutateAsync: saveAdminDeclaration, isPending: isSaving } =
    useUpdateAdminDeclaration();
  const { mutateAsync: publishDeclaration, isPending: isPublishing } =
    usePublishAdminDeclaration();

  const isPublished = declaration?.adminDeclarationStatus === "PUBLISHED";

  useEffect(() => {
    if (declaration?.adminAnswers?.questions && declaration.adminAnswers.questions.length > 0) {
      setQuestions(declaration.adminAnswers.questions);
      setHasUnsaved(false);
    } else if (declaration?.answers) {
      const derived = deriveSeedQuestions(declaration.answers, declaration.autoGeneratedData);
      if (derived.length > 0) {
        setQuestions(derived);
        setHasUnsaved(true);
      }
    }
  }, [declaration]);

  const handleAddQuestion = () => {
    setQuestions((prev) => [
      ...prev,
      {
        id: generateAdminQuestionId(),
        question: "",
        answer: "",
        createdAt: new Date().toISOString(),
      },
    ]);
    setHasUnsaved(true);
  };

  const handleDeleteQuestion = (id: string) => {
    setQuestions((prev) => prev.filter((q) => q.id !== id));
    setHasUnsaved(true);
  };

  const handleQuestionChange = (id: string, field: "question" | "answer", value: string) => {
    setQuestions((prev) =>
      prev.map((q) => (q.id === id ? { ...q, [field]: value } : q)),
    );
    setHasUnsaved(true);
  };

  const handleSave = useCallback(async () => {
    try {
      await saveAdminDeclaration({
        appId,
        adminAnswers: { questions },
      });
      setHasUnsaved(false);
      toast({
        title: "Saved",
        description: "Admin declaration saved successfully.",
      });
    } catch (err: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: err?.message || "Failed to save admin declaration.",
      });
    }
  }, [appId, questions, saveAdminDeclaration]);

  const handlePublish = useCallback(async () => {
    try {
      await publishDeclaration({ appId });
      toast({
        title: "Published",
        description: "Declaration is now visible to the app owner.",
      });
    } catch (err: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: err?.message || "Failed to publish declaration.",
      });
    }
  }, [appId, publishDeclaration]);

  if (isPending) {
    return (
      <Card className="border border-border/50 shadow-sm bg-card rounded-3xl">
        <CardContent className="p-12 flex items-center justify-center">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className="border border-border/50 shadow-sm bg-card rounded-3xl">
        <CardContent className="p-12 flex flex-col items-center justify-center gap-4">
          <AlertCircle className="w-10 h-10 text-destructive" />
          <p className="text-muted-foreground text-center">
            {error.message || "Failed to load declaration"}
          </p>
          <Button variant="outline" onClick={() => refetch()}>
            Retry
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border border-border/50 shadow-sm bg-card rounded-3xl overflow-hidden">
      <CardHeader className="bg-primary/5 border-b border-border/50 pb-4">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2 text-primary">
            <FileText className="w-5 h-5" />
            Admin Declaration
          </CardTitle>
          <div className="flex items-center gap-2">
            {isPublished ? (
              <Badge className="bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/20 font-bold">
                <CheckCircle2 className="w-3.5 h-3.5 mr-1" />
                Published
              </Badge>
            ) : (
              <Badge variant="outline" className="font-bold">
                Draft
              </Badge>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6 space-y-6">
        {questions.length === 0 && !isPublished && (
          <div className="text-center py-8 text-muted-foreground">
            <FileText className="w-10 h-10 mx-auto mb-3 opacity-40" />
            <p className="font-medium">
              No declaration content available yet.
            </p>
            <p className="text-sm">
              The developer has not filled out their declaration.               Click &quot;Add
              Question&quot; to build one from scratch.
            </p>
          </div>
        )}

        {questions.map((q, index) => (
          <div
            key={q.id}
            className="p-5 rounded-2xl border border-border/50 bg-background/50 space-y-4 relative group"
          >
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
                Question {index + 1}
              </span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleDeleteQuestion(q.id)}
                className="h-8 w-8 p-0 rounded-lg text-muted-foreground hover:text-destructive opacity-40 group-hover:opacity-100 transition-opacity"
              >
                <Trash2 className="w-4 h-4" />
              </Button>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-foreground">
                Question
              </label>
              <Textarea
                value={q.question}
                onChange={(e) =>
                  handleQuestionChange(q.id, "question", e.target.value)
                }
                placeholder="Enter the question..."
                className="min-h-[60px] resize-none rounded-xl"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-foreground">
                Answer
              </label>
              <Textarea
                value={q.answer}
                onChange={(e) =>
                  handleQuestionChange(q.id, "answer", e.target.value)
                }
                placeholder="Enter the answer..."
                className="min-h-[80px] resize-none rounded-xl"
              />
            </div>
          </div>
        ))}

        <Button
          variant="outline"
          onClick={handleAddQuestion}
          className="w-full py-6 rounded-2xl border-dashed border-2 hover:border-primary/50 transition-colors"
        >
          <Plus className="w-4 h-4 mr-2" />
          Add Question
        </Button>
      </CardContent>
      <CardFooter className="p-6 bg-secondary/30 border-t border-border/50 flex flex-wrap items-center justify-between gap-4">
        <p className="text-xs text-muted-foreground">
          {hasUnsaved && (
            <span className="text-amber-600 dark:text-amber-400 font-medium">
              {declaration?.adminAnswers?.questions?.length
                ? "You have unsaved changes."
                : "Seeded with auto-generated answers, save to create your draft."}
            </span>
          )}
          {!hasUnsaved && questions.length > 0 && (
            <span className="text-emerald-600 dark:text-emerald-400 font-medium">
              All changes saved.
            </span>
          )}
        </p>
        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            onClick={handleSave}
            disabled={isSaving || !hasUnsaved}
            className="rounded-xl"
          >
            {isSaving ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Save className="w-4 h-4 mr-2" />
            )}
            Save
          </Button>
          {!isPublished && questions.length > 0 && (
            <Button
              onClick={handlePublish}
              disabled={isPublishing || hasUnsaved}
              className="rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white shadow-lg shadow-emerald-600/20"
            >
              {isPublishing ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Send className="w-4 h-4 mr-2" />
              )}
              Publish Declaration
            </Button>
          )}
        </div>
      </CardFooter>
    </Card>
  );
}
