import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { DeclarationAnswers, AutoGeneratedStats } from "@/lib/types";

const colors = {
  primary: "#2563eb",
  primaryLight: "#dbeafe",
  text: "#1e293b",
  textSecondary: "#64748b",
  border: "#e2e8f0",
  background: "#ffffff",
};

const styles = StyleSheet.create({
  page: {
    padding: 40,
    paddingBottom: 60,
    backgroundColor: colors.background,
    color: colors.text,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  coverPage: {
    paddingTop: 120,
    paddingHorizontal: 40,
    paddingBottom: 60,
    backgroundColor: colors.background,
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: colors.primary,
    marginBottom: 8,
    fontFamily: "Helvetica-Bold",
  },
  coverSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 40,
    fontFamily: "Helvetica",
  },
  coverDetails: {
    fontSize: 11,
    color: colors.text,
    marginBottom: 4,
    lineHeight: 1.6,
  },
  coverDivider: {
    borderBottom: `1px solid ${colors.border}`,
    marginVertical: 30,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: colors.primary,
    marginBottom: 12,
    paddingBottom: 6,
    borderBottom: `2px solid ${colors.primary}`,
    fontFamily: "Helvetica-Bold",
  },
  subSectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: colors.text,
    marginBottom: 6,
    marginTop: 8,
    fontFamily: "Helvetica-Bold",
  },
  question: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.text,
    marginBottom: 4,
    marginTop: 12,
    fontFamily: "Helvetica-Bold",
  },
  answer: {
    fontSize: 10,
    color: colors.textSecondary,
    lineHeight: 1.5,
    marginBottom: 8,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    width: "23%",
    padding: 10,
    backgroundColor: colors.primaryLight,
    borderRadius: 8,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: 700,
    color: colors.primary,
    fontFamily: "Helvetica-Bold",
  },
  statLabel: {
    fontSize: 8,
    color: colors.textSecondary,
    marginTop: 2,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: colors.textSecondary,
    borderTop: `1px solid ${colors.border}`,
    paddingTop: 8,
  },
  divider: {
    borderBottom: `1px solid ${colors.border}`,
    marginVertical: 8,
  },
});

function StatBox({ label, value }: { label: string; value: string | number }) {
  return (
    <View style={styles.statCard}>
      <Text style={styles.statValue}>{value}</Text>
      <Text style={styles.statLabel}>{label}</Text>
    </View>
  );
}

function QuestionAnswer({
  number,
  question,
  answer,
}: {
  number: number;
  question: string;
  answer: string;
}) {
  return (
    <View>
      <Text style={styles.question}>
        {number}. {question}
      </Text>
      <Text style={styles.answer}>{answer || "Not provided"}</Text>
    </View>
  );
}

function DocFooter({ appName }: { appName: string }) {
  return (
    <Text style={styles.footer} fixed>
      Generated by inTesters Platform | {appName} | {new Date().toLocaleDateString()}
    </Text>
  );
}

export function DeclarationPDFDocument({
  answers,
  stats,
  appName,
  packageName,
  category,
  deletedQuestions = [],
}: {
  answers: DeclarationAnswers;
  stats: AutoGeneratedStats;
  appName: string;
  packageName: string;
  category: string;
  deletedQuestions?: string[];
}) {
  const customQuestions = answers.customQuestions || [];
  const isDeleted = (id: string) => deletedQuestions.includes(id);

  const part1Questions = [
    { id: "recruitmentMethod", num: 1, q: "How did you recruit users for your closed test?", a: answers.recruitmentMethod },
    { id: "recruitmentEase", num: 2, q: "How easy was it to recruit testers for your app?", a: answers.recruitmentEase },
    { id: "testerEngagement", num: 3, q: "Describe the engagement you received from testers during your closed test.", a: answers.testerEngagement },
    { id: "feedbackSummary", num: 4, q: "Provide a summary of the feedback that you received from testers.", a: answers.feedbackSummary },
    { id: "feedbackCollectionMethod", num: 5, q: "How did you collect the feedback?", a: answers.feedbackCollectionMethod },
  ].filter((q) => !isDeleted(q.id));

  const part2Questions = [
    { id: "intendedAudience", num: 6, q: "Who is the intended audience of your app?", a: answers.intendedAudience },
    { id: "valueDescription", num: 7, q: "Describe how your app provides value to users.", a: answers.valueDescription },
    { id: "expectedInstalls", num: 8, q: "How many installs do you expect your app to have in its first year?", a: answers.expectedInstalls },
  ].filter((q) => !isDeleted(q.id));

  const part3Questions = [
    { id: "changesMade", num: 9, q: "What changes did you make to your app based on what you learned during your closed test?", a: answers.changesMade },
    { id: "readinessRationale", num: 10, q: "How did you decide that your app is ready for production?", a: answers.readinessRationale },
  ].filter((q) => !isDeleted(q.id));

  return (
    <Document>
      <Page size="A4" style={styles.coverPage}>
        <Text style={styles.coverTitle}>Testing Summary Report</Text>
        <Text style={styles.coverSubtitle}>Google Play Production Access Declaration</Text>

        <View style={styles.coverDivider} />

        <Text style={styles.coverDetails}>App Name: {appName}</Text>
        <Text style={styles.coverDetails}>Package Name: {packageName}</Text>
        <Text style={styles.coverDetails}>Category: {category}</Text>
        <Text style={styles.coverDetails}>Testing Type: {stats.appType === "PAID" ? "Paid Professional Testing" : "Community Testing"}</Text>
        <Text style={styles.coverDetails}>
          Testing Period: {stats.totalDays} days
        </Text>
        <Text style={styles.coverDetails}>
          Generated: {new Date().toLocaleDateString()}
        </Text>

        <View style={styles.coverDivider} />

        <Text style={{ fontSize: 10, color: colors.textSecondary, lineHeight: 1.6 }}>
          This report summarizes the closed testing results for {appName}. It includes
          aggregated testing metrics, tester feedback analysis, and the completed
          Google Play production access declaration form. This document is prepared
          to support the production release application on Google Play Store.
        </Text>

        <DocFooter appName={appName} />
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Testing Summary</Text>

        <View style={styles.statsGrid}>
          <StatBox label="Total Testers" value={stats.totalTesters} />
          <StatBox label="Completed" value={stats.completedTesters} />
          <StatBox label="Duration" value={`${stats.totalDays} Days`} />
          <StatBox label="Avg Rating" value={stats.avgRating !== null ? `${stats.avgRating}/5` : "N/A"} />
          <StatBox label="Bugs" value={stats.bugs} />
          <StatBox label="Suggestions" value={stats.suggestions} />
          <StatBox label="Praise" value={stats.praise} />
          <StatBox label="Total Feedback" value={stats.totalFeedback} />
        </View>

        <View style={styles.divider} />

        <Text style={styles.subSectionTitle}>Key Testing Metrics</Text>
        <Text style={styles.answer}>
          This app was tested through the inTesters platform with {stats.totalTesters} testers,
          of whom {stats.completedTesters} completed the full {stats.totalDays}-day testing period.
          Testers submitted {stats.totalFeedback} feedback items including {stats.bugs} bug reports,
          {stats.suggestions} suggestions, and {stats.praise} praise items.
          {stats.avgRating !== null ? ` The app received an average rating of ${stats.avgRating} out of 5.` : ""}
        </Text>

        <DocFooter appName={appName} />
      </Page>

      {part1Questions.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Part 1: About Your Closed Test</Text>

          {part1Questions.map((q) => (
            <QuestionAnswer key={q.id} number={q.num} question={q.q} answer={q.a} />
          ))}

          <DocFooter appName={appName} />
        </Page>
      )}

      {part2Questions.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Part 2: About Your App</Text>

          {part2Questions.map((q) => (
            <QuestionAnswer key={q.id} number={q.num} question={q.q} answer={q.a} />
          ))}

          <DocFooter appName={appName} />
        </Page>
      )}

      {part3Questions.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Part 3: Production Readiness</Text>

          {part3Questions.map((q) => (
            <QuestionAnswer key={q.id} number={q.num} question={q.q} answer={q.a} />
          ))}

          <DocFooter appName={appName} />
        </Page>
      )}

      {customQuestions.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Part 4: Custom Questions</Text>
          {customQuestions.map((cq, index) => (
            <QuestionAnswer
              key={cq.id}
              number={11 + index}
              question={cq.question || "Custom Question"}
              answer={cq.answer}
            />
          ))}

          <DocFooter appName={appName} />
        </Page>
      )}
    </Document>
  );
}
