"use client";

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence, LayoutGroup } from "framer-motion";
import { PDFDownloadLink } from "@react-pdf/renderer";
import {
  BarChart3,
  FileText,
  FileDown,
  Loader2,
  AlertCircle,
  RefreshCw,
  Eye,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useDeclaration, useUpdateDeclaration } from "@/hooks/use-declaration";
import type { DeclarationAnswers, AutoGeneratedStats, HubSubmittedAppResponse } from "@/lib/types";
import { DeclarationSummaryCards } from "./declaration-summary-cards";
import { DeclarationQuestionnaire } from "./declaration-questionnaire";
import { DeclarationPDFDocument } from "./declaration-pdf-document";
import { ReportPreparing } from "./report-preparing";
import { getDefaultAnswer } from "@/lib/declaration-helpers";

const DEFAULT_ANSWERS: DeclarationAnswers = {
  recruitmentMethod: "",
  recruitmentEase: "",
  testerEngagement: "",
  feedbackSummary: "",
  feedbackCollectionMethod: "",
  intendedAudience: "",
  valueDescription: "",
  expectedInstalls: "",
  changesMade: "",
  readinessRationale: "",
  customQuestions: [],
  deletedQuestions: [],
};

const DEFAULT_STATS: AutoGeneratedStats = {
  totalTesters: 0,
  completedTesters: 0,
  totalDays: 0,
  currentDay: 0,
  bugs: 0,
  suggestions: 0,
  praise: 0,
  totalFeedback: 0,
  totalRatings: 0,
  avgRating: null,
  appType: "FREE",
  hasCriticalBugs: false,
  testingStartDate: null,
  testingEndDate: null,
  packageName: "",
  category: "",
};

export function DeclarationReport({
  appId,
  appDetails,
  onClose,
}: {
  appId: string | number;
  appDetails?: HubSubmittedAppResponse;
  onClose?: () => void;
}) {
  const [activeTab, setActiveTab] = useState("summary");
  const [answers, setAnswers] = useState<DeclarationAnswers>(DEFAULT_ANSWERS);

  const { data: declaration, isPending, error, refetch } = useDeclaration(appId);
  const { mutateAsync: updateDeclaration } = useUpdateDeclaration();

  const stats: AutoGeneratedStats =
    declaration?.autoGeneratedData || DEFAULT_STATS;

  const adminQuestions = declaration?.adminAnswers?.questions;
  const isPaidApp = stats.appType === "PAID";

  useEffect(() => {
    if (declaration?.answers) {
      const isFreeApp = stats.appType === "FREE";
      const needsSeeding =
        isFreeApp &&
        !declaration.answers.recruitmentMethod &&
        !declaration.answers.recruitmentEase &&
        !declaration.answers.testerEngagement &&
        !declaration.answers.feedbackSummary &&
        !declaration.answers.feedbackCollectionMethod &&
        !declaration.answers.intendedAudience &&
        !declaration.answers.valueDescription &&
        !declaration.answers.expectedInstalls &&
        !declaration.answers.changesMade &&
        !declaration.answers.readinessRationale;

      if (needsSeeding && stats) {
        const seededAnswers = {
          ...DEFAULT_ANSWERS,
          ...declaration.answers,
          recruitmentMethod: getDefaultAnswer("recruitmentMethod", stats),
          recruitmentEase: getDefaultAnswer("recruitmentEase", stats),
          testerEngagement: getDefaultAnswer("testerEngagement", stats),
          feedbackSummary: getDefaultAnswer("feedbackSummary", stats),
          feedbackCollectionMethod: getDefaultAnswer("feedbackCollectionMethod", stats),
          intendedAudience: getDefaultAnswer("intendedAudience", stats),
          valueDescription: getDefaultAnswer("valueDescription", stats),
          expectedInstalls: getDefaultAnswer("expectedInstalls", stats),
          changesMade: getDefaultAnswer("changesMade", stats),
          readinessRationale: getDefaultAnswer("readinessRationale", stats),
          customQuestions: declaration.answers.customQuestions || [],
          deletedQuestions: declaration.answers.deletedQuestions || [],
        };
        setAnswers(seededAnswers);
        updateDeclaration({ appId, answers: seededAnswers }).catch(console.error);
      } else {
        setAnswers({
          ...DEFAULT_ANSWERS,
          ...declaration.answers,
          customQuestions: declaration.answers.customQuestions || [],
          deletedQuestions: declaration.answers.deletedQuestions || [],
        });
      }
    }
  }, [declaration, stats, appId, updateDeclaration]);

  const handleAnswersChange = useCallback(
    (newAnswers: DeclarationAnswers) => {
      setAnswers(newAnswers);
      updateDeclaration({ appId, answers: newAnswers }).catch(console.error);
    },
    [appId, updateDeclaration],
  );

  if (isPending) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-20 gap-4">
        <AlertCircle className="w-12 h-12 text-destructive" />
        <p className="text-muted-foreground">
          {(error as any)?.response?.data?.message || error.message || "Failed to load declaration"}
        </p>
        <Button variant="outline" onClick={() => refetch()}>
          <RefreshCw className="w-4 h-4 mr-2" />
          Retry
        </Button>
      </div>
    );
  }

  const isPaid = declaration?.autoGeneratedData?.appType === "PAID";
  const isPublished = declaration?.adminDeclarationStatus === "PUBLISHED";
  const showPreparing = !declaration || (isPaid && !isPublished);

  const appName = appDetails?.androidApp?.appName || stats.packageName || "App";
  const packageName = appDetails?.androidApp?.packageName || stats.packageName;
  const category = appDetails?.androidApp?.appCategory?.name || stats.category;

  return (
    <div className="space-y-6 mb-6">

      {showPreparing ? (
        <ReportPreparing onRefetch={refetch} />
      ) : (
        <div className="w-full">
          <LayoutGroup>
            <div className="flex items-center gap-0 border-b border-border/30">
              {[
                { value: "summary", icon: BarChart3, label: "Summary" },
                { value: "questions", icon: FileText, label: "Declaration" },
                { value: "download", icon: FileDown, label: "Download PDF" },
              ].map((tab) => {
                const Icon = tab.icon;
                return (
                  <button
                    key={tab.value}
                    onClick={() => setActiveTab(tab.value)}
                    className={`relative px-4 py-3 text-sm font-medium transition-colors duration-200 ${
                      activeTab === tab.value
                        ? "text-primary"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    <span className="flex items-center gap-2 whitespace-nowrap">
                      <Icon className="w-4 h-4" />
                      <span>{tab.label}</span>
                    </span>
                    {activeTab === tab.value && (
                      <motion.div
                        layoutId="tab-underline"
                        className="absolute bottom-0 left-0 right-0 h-[2px] bg-primary"
                      />
                    )}
                  </button>
                );
              })}
            </div>
          </LayoutGroup>

          <div className="relative pt-6">
            <AnimatePresence mode="wait">
              {activeTab === "summary" && (
                <motion.div
                  key="summary"
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.2 }}
                >
                  <DeclarationSummaryCards stats={stats} />
                </motion.div>
              )}

              {activeTab === "questions" && (
                <motion.div
                  key="questions"
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.2 }}
                >
                  <DeclarationQuestionnaire
                    answers={answers}
                    onChange={handleAnswersChange}
                    onSave={async (newAnswers: DeclarationAnswers) => {
                      setAnswers(newAnswers);
                      await updateDeclaration({ appId, answers: newAnswers });
                    }}
                    adminQuestions={adminQuestions}
                  />
                </motion.div>
              )}

              {activeTab === "download" && (
                <motion.div
                  key="download"
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.2 }}
                >
                  <div className="rounded-2xl bg-card p-8 max-w-2xl mx-auto text-center">
                  <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-6">
                    <FileDown className="w-8 h-8 text-primary" />
                  </div>
                  <h3 className="text-xl font-bold mb-2">Download PDF Report</h3>
                  <p className="text-sm text-muted-foreground mb-8 max-w-md mx-auto">
                    Download a complete PDF report containing all testing metrics and your
                    Google Play declaration answers. Use this as reference when submitting
                    your production access application.
                  </p>

                  <PDFDownloadLink
                    document={
                  <DeclarationPDFDocument
                      answers={answers}
                      stats={stats}
                      appName={appName}
                      packageName={packageName}
                      category={category}
                      deletedQuestions={answers.deletedQuestions}
                      adminQuestions={adminQuestions}
                    />
                    }
                    fileName={`${appName.replace(/\s+/g, "_")}_Testing_Report.pdf`}
                    className="inline-block"
                  >
                    {({ loading }: { loading: boolean }) => (
                      <Button
                        size="lg"
                        disabled={loading}
                        className="gap-3 min-w-[240px]"
                      >
                        {loading ? (
                          <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                            Generating PDF...
                          </>
                        ) : (
                          <>
                            <FileDown className="w-5 h-5" />
                            Download PDF Report
                          </>
                        )}
                      </Button>
                    )}
                  </PDFDownloadLink>

                  <div className="mt-8 text-left bg-muted/50 rounded-xl p-4 text-xs text-muted-foreground space-y-2">
                    <p className="flex items-center gap-2">
                      <Eye className="w-3.5 h-3.5" />
                      <strong>The PDF includes:</strong>
                    </p>
                    <ul className="list-disc pl-6 space-y-1">
                      <li>Cover page with app details and executive summary</li>
                      <li>Testing metrics dashboard (testers, feedback, ratings)</li>
                      {isPaidApp ? (
                        <li>Admin declaration questions &amp; answers (prepared by our team)</li>
                      ) : (
                        <li>All Google Play declaration questions with your answers</li>
                      )}
                      <li>Your custom questions and answers</li>
                      <li>Formatted for easy reference</li>
                    </ul>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
          </div>
        </div>
      )}
    </div>
  );
}
