import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import type { DeclarationAnswers, AutoGeneratedStats, AdminQuestion } from "@/lib/types";

const LOGO_BASE64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAFHklEQVR4nO2dTZKcMAyFfYk+EtWbHCYbrsRVOAgHITUpmHEbmzGgH0t+i1epTHqaDvqsJ2Q1hPffPwHqV+ofAAIAEACAAAAEACAAAAEACABAAAACABAAgAAABAAgAAABAAgAQH4ACCG8QghDQV//9tI+OT1II+hjCGEKISyb1oy+fj5vrx0q33vY3nfe/qxV6fXpz/e/j9pBMwdAFPhSwM+0bL97mhG24Fx97zuatINmCoBtZc4EJ34uQbABRnGMGiEDXAz+nVVfXH05CBiOc5aNqizJiiwFv7gCt2NJrP7FW3HKFfwXoycfrAD+3x4Ao1Qahv83BoBQQFIAJPx/9eb/XABI+PEofLzVo/9zAcCZ/nMZQOJ4X5q1g2UFAImCbHjD/7sF4DsVw//7BGCOjgX/bxAAbk8eBY/1DR0AqAeAc1V+BELQ/901gDgB4CrMcg0gKf93WQCyAPDmS81jcgwp/1+9FoBsABBDsBQ2gOD/jQPwIgjSXFp98P/GAYgCtQ+EXPHr+WwKCP5vCIAoYEM0DzhHM4FLPG+3D4VWQCUR/NWz/4sBUADiQxd/X8r/3TaAVAEgAEhqAMR1AUgCQDSOLSkp/18U/m+SGiytRohezwAQ3o6FaPXf3igAkErHEK2mxzWA8OUYRKuRAgCpyzGIXgMFAPB/m/qZqoL/d6mfqSr4f5caKQCA/9sVCQBoANnU52TVA/9HAWhTn3OVD/wfBaBNfQy4wP/700gBAPzfpg53OIH/96XDgMtdADj9f8mMjGmfOC86DLjeLQA5gz8k42KSBecOn1cdx+sbKwCPKUq24zhGWc6dsvG8AQCn/x9TlOwAqOsJ4McACPh/7htAGABtCADudDwkx5PccXT9DSAqANz7f2+6CgBnOj7chEm449id/18CQKABpOn/7r8BRAEA9/V4zv+lOo5dFoB3AOBcgSkAkg2gLgvAqwCw+n+mAJT0/y4LwKsASDeAJP2/ywKwGgDpBpCw/3dbAF4BQNr/0QBqDABOP875PxpArQDA/PSP7ApEA6g9AKQ3gCT9HwD8AoDnDaBuG0BXAPC8AdR1AVgLABpAjvVb8LmvxzUbQGvv/l8DgMYGkOQAaNf+XwsAZwByG0BSq7/7ArAGAM/+330BeApAB/7ffQFYA4DXDSAAUAGA5wbQ4fi96gwAzw2g7lvANQBwpmPtCWBkgDMAlDaApAFADXACgKj/v3VuOoE+wAkAov6vBMC6HbNrCEoAiDaA3rq3nd0fUJXel+DR166tKBd88QaQYgaItTy4QYRZCHKBEN0AagiAJxnEFQDi/i9wXE6Z3lOQXonFk2UYANOXk7lAcPp/sfli+O6jphtKaRA4G0Cnl1xG7z9ofqgktwrVVopBGzDt/zkAuAJQ1XAx+BQS0/6fA4CjALy082YsC5j2/w8AGFffpVViqBYw7/8pABz+f6vXbuSKwHQDKAcAdep9dIIMWIH5AjAFgNL/Zwp/bBwC8wXgNwDEvksS/ASC1uzAzUjZfpKpPJdlf73BmsCF/8cAPE21y/YebCdF4EYVl0DXDlxLAEyS6XDLBtoguPD/7Xze8v9lD7xGKoyeJDIpWYML/48BqDmJSzw+pf3BExhGQRhcNIBiAIZoHCodi5rSeTntD1wBwxABET98iiLwiyf/f0cZwNWgYwLEDsUORqypoPR1g5bdsZ8j7Q8AAQAIAEAAAAIAEACAAAAEACAAAAEACABAAAACABAAgAAABAAgcv0DDG7HsmuoEj4AAAAASUVORK5CYII=";

const colors = {
  primary: "#2563eb",
  primaryDark: "#1d4ed8",
  primaryLight: "#eff6ff",
  dark: "#0f172a",
  text: "#334155",
  textSecondary: "#64748b",
  textMuted: "#94a3b8",
  border: "#e2e8f0",
  lightBg: "#f8fafc",
  white: "#ffffff",
  bug: "#ea580c",
  praise: "#16a34a",
  suggestion: "#7c3aed",
  tester: "#2563eb",
  customAccent: "#7c3aed",
};

const styles = StyleSheet.create({
  page: {
    padding: 44,
    paddingBottom: 64,
    backgroundColor: colors.white,
    color: colors.text,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  coverPage: {
    padding: 0,
    backgroundColor: colors.white,
  },
  coverTopBar: {
    backgroundColor: colors.primary,
    paddingHorizontal: 60,
    paddingVertical: 20,
    marginBottom: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  coverLogo: {
    width: 24,
    height: 24,
  },
  coverTopBarText: {
    fontSize: 11,
    color: colors.white,
    fontFamily: "Helvetica",
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  coverTitle: {
    fontSize: 34,
    fontWeight: 700,
    color: colors.dark,
    marginBottom: 6,
    fontFamily: "Helvetica-Bold",
    paddingHorizontal: 60,
  },
  coverPackageName: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 36,
    fontFamily: "Helvetica",
    paddingHorizontal: 60,
  },
  coverMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 60,
    marginBottom: 28,
  },
  coverMetaItem: {
    width: "50%",
    marginBottom: 10,
  },
  coverMetaLabel: {
    fontSize: 7,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 2,
    fontFamily: "Helvetica",
  },
  coverMetaValue: {
    fontSize: 11,
    color: colors.dark,
    fontFamily: "Helvetica-Bold",
  },
  coverAccentLine: {
    marginHorizontal: 60,
    marginBottom: 28,
    borderBottom: `2px solid ${colors.primary}`,
    width: 60,
  },
  coverDescription: {
    fontSize: 10,
    color: colors.textSecondary,
    lineHeight: 1.7,
    paddingHorizontal: 60,
    marginBottom: 48,
  },
  coverDateBadgeContainer: {
    paddingHorizontal: 60,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  coverDateBadge: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
  },
  coverDateBadgeText: {
    fontSize: 8,
    color: colors.primary,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.5,
  },
  coverFooter: {
    position: "absolute",
    bottom: 36,
    left: 60,
    right: 60,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  coverFooterText: {
    fontSize: 8,
    color: colors.textMuted,
    fontFamily: "Helvetica",
  },
  coverFooterDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: colors.primary,
    marginHorizontal: 6,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.dark,
    fontFamily: "Helvetica-Bold",
    marginBottom: 16,
    paddingBottom: 10,
    borderBottom: `1px solid ${colors.border}`,
  },
  sectionTitleBullet: {
    width: 6,
    height: 6,
    backgroundColor: colors.primary,
    borderRadius: 1,
    marginRight: 8,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitleText: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.dark,
    fontFamily: "Helvetica-Bold",
  },
  subSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.dark,
    marginBottom: 10,
    marginTop: 6,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  execSummaryBox: {
    backgroundColor: colors.primaryLight,
    borderRadius: 6,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    padding: 14,
    marginBottom: 20,
  },
  execSummaryText: {
    fontSize: 10,
    color: colors.text,
    lineHeight: 1.7,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 8,
    marginHorizontal: -4,
  },
  statCard: {
    width: "25%",
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  statCardInner: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    padding: 12,
    position: "relative",
    backgroundColor: colors.white,
  },
  statCardDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 700,
    color: colors.dark,
    fontFamily: "Helvetica-Bold",
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 7,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontFamily: "Helvetica",
  },

  qaCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    padding: 14,
    marginBottom: 10,
    backgroundColor: colors.white,
  },
  qaCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
  },
  qaNumberBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginTop: 1,
    flexShrink: 0,
  },
  qaNumberBadgeText: {
    fontSize: 9,
    color: colors.white,
    fontFamily: "Helvetica-Bold",
  },
  qaQuestionText: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.dark,
    fontFamily: "Helvetica-Bold",
    lineHeight: 1.5,
    flex: 1,
  },
  qaAnswerText: {
    fontSize: 10,
    color: colors.text,
    lineHeight: 1.7,
    marginLeft: 30,
  },
  qaAnswerEmpty: {
    fontSize: 10,
    color: colors.textMuted,
    marginLeft: 30,
    fontFamily: "Helvetica-Oblique",
  },
  customAccentLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: colors.customAccent,
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
  },
  primaryAccentLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: colors.primary,
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
  },
  adminAccentLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: colors.textMuted,
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
  },
  divider: {
    borderBottom: `1px solid ${colors.border}`,
    marginVertical: 12,
  },
  dividerWithDot: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 16,
  },
  dividerLine: {
    flex: 1,
    borderBottom: `1px solid ${colors.border}`,
  },
  dividerDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: colors.primary,
    marginHorizontal: 8,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 44,
    right: 44,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTop: `0.5px solid ${colors.border}`,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 7,
    color: colors.textMuted,
    fontFamily: "Helvetica",
  },
  footerCenter: {
    fontSize: 7,
    color: colors.textMuted,
    fontFamily: "Helvetica",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
});

function StatCard({
  label,
  value,
  dotColor,
}: {
  label: string;
  value: string | number;
  dotColor?: string;
}) {
  return (
    <View style={styles.statCard}>
      <View style={styles.statCardInner}>
        <Text style={styles.statValue}>{value}</Text>
        <Text style={styles.statLabel}>{label}</Text>
      </View>
    </View>
  );
}

function QuestionAnswer({
  number,
  question,
  answer,
  isCustom = false,
  isAdmin = false,
}: {
  number: number;
  question: string;
  answer: string;
  isCustom?: boolean;
  isAdmin?: boolean;
}) {
  const accentBar = isCustom
    ? styles.customAccentLeft
    : isAdmin
      ? styles.adminAccentLeft
      : styles.primaryAccentLeft;
  const badgeBg = isCustom
    ? colors.customAccent
    : isAdmin
      ? colors.textMuted
      : colors.primary;

  return (
    <View style={styles.qaCard} wrap={false}>
      <View style={accentBar} />
      <View style={styles.qaCardHeader}>
        <View style={[styles.qaNumberBadge, { backgroundColor: badgeBg }]}>
          <Text style={styles.qaNumberBadgeText}>{number}</Text>
        </View>
        <Text style={styles.qaQuestionText}>{question}</Text>
      </View>
      {answer ? (
        <Text style={styles.qaAnswerText}>{answer}</Text>
      ) : (
        <Text style={styles.qaAnswerEmpty}>No answer provided</Text>
      )}
    </View>
  );
}

function SectionDivider() {
  return (
    <View style={styles.dividerWithDot}>
      <View style={styles.dividerLine} />
      <View style={styles.dividerDot} />
      <View style={styles.dividerLine} />
    </View>
  );
}

function DocFooter({ appName }: { appName: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>inTesters Platform</Text>
      <Text style={styles.footerCenter}>
        Confidential &bull; {new Date().toLocaleDateString()}
      </Text>
      <Text style={styles.footerText}>{appName}</Text>
    </View>
  );
}

function renderStars(rating: number | null): string {
  if (rating === null) return "—";
  const full = Math.floor(rating);
  const half = rating - full >= 0.5;
  let stars = "★".repeat(full);
  if (half) stars += "☆";
  stars += "☆".repeat(Math.max(0, 5 - full - (half ? 1 : 0)));
  return stars;
}

export function DeclarationPDFDocument({
  answers,
  stats,
  appName,
  packageName,
  category,
  deletedQuestions = [],
  adminQuestions,
}: {
  answers: DeclarationAnswers;
  stats: AutoGeneratedStats;
  appName: string;
  packageName: string;
  category: string;
  deletedQuestions?: string[];
  adminQuestions?: AdminQuestion[];
}) {
  const customQuestions = answers.customQuestions || [];
  const isDeleted = (id: string) => deletedQuestions.includes(id);
  const showAdminQuestions = adminQuestions && adminQuestions.length > 0;

  const part1Questions = [
    { id: "recruitmentMethod", num: 1, q: "How did you recruit users for your closed test?", a: answers.recruitmentMethod },
    { id: "recruitmentEase", num: 2, q: "How easy was it to recruit testers for your app?", a: answers.recruitmentEase },
    { id: "testerEngagement", num: 3, q: "Describe the engagement you received from testers during your closed test.", a: answers.testerEngagement },
    { id: "feedbackSummary", num: 4, q: "Provide a summary of the feedback that you received from testers.", a: answers.feedbackSummary },
    { id: "feedbackCollectionMethod", num: 5, q: "How did you collect the feedback?", a: answers.feedbackCollectionMethod },
  ].filter((q) => !isDeleted(q.id));

  const part2Questions = [
    { id: "intendedAudience", num: 6, q: "Who is the intended audience of your app?", a: answers.intendedAudience },
    { id: "valueDescription", num: 7, q: "Describe how your app provides value to users.", a: answers.valueDescription },
    { id: "expectedInstalls", num: 8, q: "How many installs do you expect your app to have in its first year?", a: answers.expectedInstalls },
  ].filter((q) => !isDeleted(q.id));

  const part3Questions = [
    { id: "changesMade", num: 9, q: "What changes did you make to your app based on what you learned during your closed test?", a: answers.changesMade },
    { id: "readinessRationale", num: 10, q: "How did you decide that your app is ready for production?", a: answers.readinessRationale },
  ].filter((q) => !isDeleted(q.id));

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.coverPage}>
          <View style={styles.coverTopBar}>
            <Image src={LOGO_BASE64} style={styles.coverLogo} />
            <Text style={styles.coverTopBarText}>Testing Summary Report</Text>
          </View>

        <Text style={styles.coverTitle}>{appName}</Text>
        <Text style={styles.coverPackageName}>{packageName}</Text>

        <View style={styles.coverMetaGrid}>
          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>Category</Text>
            <Text style={styles.coverMetaValue}>{category || "—"}</Text>
          </View>
          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>Testing Type</Text>
            <Text style={styles.coverMetaValue}>
              {stats.appType === "PAID" ? "Paid Professional Testing" : "Community Testing"}
            </Text>
          </View>
          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>Testing Duration</Text>
            <Text style={styles.coverMetaValue}>{stats.totalDays} Days</Text>
          </View>
          <View style={styles.coverMetaItem}>
            <Text style={styles.coverMetaLabel}>Total Testers</Text>
            <Text style={styles.coverMetaValue}>{stats.totalTesters}</Text>
          </View>
        </View>

        <View style={styles.coverAccentLine} />

        <Text style={styles.coverDescription}>
          This report summarizes the closed testing results for {appName}. It includes
          aggregated testing metrics, tester feedback analysis, and the completed
          declaration form. This document is prepared to support the production release
          application on Google Play Store.
        </Text>

        <View style={styles.coverDateBadgeContainer}>
          <View style={styles.coverDateBadge}>
            <Text style={styles.coverDateBadgeText}>Generated {today}</Text>
          </View>
        </View>

        <DocFooter appName={appName} />
      </Page>

      <Page size="A4" style={styles.page}>
        <View style={styles.sectionTitleRow}>
          <View style={styles.sectionTitleBullet} />
          <Text style={styles.sectionTitleText}>Testing Summary</Text>
        </View>

        <View style={styles.execSummaryBox}>
          <Text style={styles.execSummaryText}>
            This app was tested through the inTesters platform with {stats.totalTesters} testers,
            of whom {stats.completedTesters} completed the full {stats.totalDays}-day testing period.
            Testers submitted {stats.totalFeedback} feedback items including {stats.bugs} bug reports,
            {stats.suggestions} suggestions, and {stats.praise} praise items.
            {stats.avgRating !== null
              ? ` The app received an average rating of ${stats.avgRating} out of 5.`
              : ""}
          </Text>
        </View>

        <Text style={styles.subSectionTitle}>Metrics Overview</Text>

        <View style={styles.statsGrid}>
          <StatCard label="Total Testers" value={stats.totalTesters} dotColor={colors.tester} />
          <StatCard label="Completed" value={stats.completedTesters} dotColor={colors.tester} />
          <StatCard label="Duration" value={`${stats.totalDays} Days`} dotColor={colors.tester} />
          <StatCard
            label="Average Rating"
            value={stats.avgRating !== null ? `${renderStars(stats.avgRating)}  ${stats.avgRating}/5` : "N/A"}
            dotColor="#f59e0b"
          />
          <StatCard label="Bugs" value={stats.bugs} dotColor={colors.bug} />
          <StatCard label="Suggestions" value={stats.suggestions} dotColor={colors.suggestion} />
          <StatCard label="Praise" value={stats.praise} dotColor={colors.praise} />
          <StatCard label="Total Feedback" value={stats.totalFeedback} dotColor={colors.praise} />
        </View>

        <SectionDivider />

        <Text style={styles.subSectionTitle}>Test Results Summary</Text>
        <Text style={{ fontSize: 10, color: colors.text, lineHeight: 1.7 }}>
          {stats.totalTesters === 0
            ? "No testing data available for this app."
            : `The closed beta test ran for ${stats.totalDays} days with ${stats.completedTesters} out of ${stats.totalTesters} testers completing the testing period. The feedback was largely ${stats.bugs > stats.praise ? "centered around bug identification" : "positive with significant praise from testers"}. ${stats.suggestions > 0 ? `Testers provided ${stats.suggestions} suggestions for improvement.` : ""}`}
        </Text>

        <DocFooter appName={appName} />
      </Page>

      {showAdminQuestions ? (
        <Page size="A4" style={styles.page}>
          <View style={styles.sectionTitleRow}>
            <View style={styles.sectionTitleBullet} />
            <Text style={styles.sectionTitleText}>Declaration Report</Text>
          </View>

          <Text style={{ fontSize: 10, color: colors.textSecondary, lineHeight: 1.6, marginBottom: 16 }}>
            The following questions and answers have been prepared by the inTesters team for
            the Google Play production access application.
          </Text>

          {adminQuestions.map((aq, index) => (
            <QuestionAnswer
              key={aq.id}
              number={index + 1}
              question={aq.question}
              answer={aq.answer}
              isAdmin
            />
          ))}

          <DocFooter appName={appName} />
        </Page>
      ) : (
        <>
          {part1Questions.length > 0 && (
            <Page size="A4" style={styles.page}>
              <View style={styles.sectionTitleRow}>
                <View style={styles.sectionTitleBullet} />
                <Text style={styles.sectionTitleText}>Part 1: About Your Closed Test</Text>
              </View>

              <Text style={{ fontSize: 10, color: colors.textSecondary, lineHeight: 1.6, marginBottom: 16 }}>
                These questions cover how you recruited testers, their engagement levels, and the
                feedback collection process during your closed beta test.
              </Text>

              {part1Questions.map((q) => (
                <QuestionAnswer key={q.id} number={q.num} question={q.q} answer={q.a} />
              ))}

              <DocFooter appName={appName} />
            </Page>
          )}

          {part2Questions.length > 0 && (
            <Page size="A4" style={styles.page}>
              <View style={styles.sectionTitleRow}>
                <View style={styles.sectionTitleBullet} />
                <Text style={styles.sectionTitleText}>Part 2: About Your App</Text>
              </View>

              <Text style={{ fontSize: 10, color: colors.textSecondary, lineHeight: 1.6, marginBottom: 16 }}>
                These questions describe your target audience, the value your app provides, and
                your expected install projections for the first year.
              </Text>

              {part2Questions.map((q) => (
                <QuestionAnswer key={q.id} number={q.num} question={q.q} answer={q.a} />
              ))}

              <DocFooter appName={appName} />
            </Page>
          )}

          {part3Questions.length > 0 && (
            <Page size="A4" style={styles.page}>
              <View style={styles.sectionTitleRow}>
                <View style={styles.sectionTitleBullet} />
                <Text style={styles.sectionTitleText}>Part 3: Production Readiness</Text>
              </View>

              <Text style={{ fontSize: 10, color: colors.textSecondary, lineHeight: 1.6, marginBottom: 16 }}>
                These questions detail the changes made based on testing feedback and your
                rationale for determining production readiness.
              </Text>

              {part3Questions.map((q) => (
                <QuestionAnswer key={q.id} number={q.num} question={q.q} answer={q.a} />
              ))}

              <DocFooter appName={appName} />
            </Page>
          )}
        </>
      )}

      {customQuestions.length > 0 && (
        <Page size="A4" style={styles.page}>
          <View style={styles.sectionTitleRow}>
            <View style={styles.sectionTitleBullet} />
            <Text style={styles.sectionTitleText}>
              {showAdminQuestions ? "Custom Questions" : "Part 4: Custom Questions"}
            </Text>
          </View>

          <Text style={{ fontSize: 10, color: colors.textSecondary, lineHeight: 1.6, marginBottom: 16 }}>
            The following custom questions were added by the developer to supplement the
            standard Google Play declaration.
          </Text>

          {customQuestions.map((cq, index) => (
            <QuestionAnswer
              key={cq.id}
              number={showAdminQuestions ? index + 1 : 11 + index}
              question={cq.question || "Custom Question"}
              answer={cq.answer}
              isCustom
            />
          ))}

          <DocFooter appName={appName} />
        </Page>
      )}
    </Document>
  );
}
