"use client";

import { motion } from "framer-motion";
import type { AutoGeneratedStats } from "@/lib/types";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.04 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 80 } },
};

interface StatCardProps {
  label: string;
  value: string | number;
}

function StatCard({ label, value }: StatCardProps) {
  return (
    <motion.div
      variants={itemVariants}
      className="rounded-xl border bg-card p-4"
    >
      <p className="text-2xl sm:text-3xl font-bold text-foreground">{value}</p>
      <p className="text-xs text-muted-foreground mt-1">{label}</p>
    </motion.div>
  );
}

export function DeclarationSummaryCards({
  stats,
}: {
  stats: AutoGeneratedStats;
}) {
  const cards = [
    {
      label: "Completed Testers",
      value: `${stats.completedTesters}/${stats.totalTesters}`,
    },
    {
      label: "Testing Duration",
      value: `${stats.totalDays} Days`,
    },
    {
      label: "Bugs Found",
      value: stats.bugs,
    },
    {
      label: "Suggestions",
      value: stats.suggestions,
    },
    {
      label: "Praise",
      value: stats.praise,
    },
    {
      label: "Average Rating",
      value: stats.avgRating !== null ? `${stats.avgRating}/5` : "N/A",
    },
    {
      label: "Total Feedback",
      value: stats.totalFeedback,
    },
    {
      label: "Test Type",
      value: stats.appType === "PAID" ? "Paid" : "Community",
    },
  ];

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3"
    >
      {cards.map((card) => (
        <StatCard key={card.label} {...card} />
      ))}
    </motion.div>
  );
}
