"use client";

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PDFDownloadLink } from "@react-pdf/renderer";
import {
  BarChart3,
  FileText,
  FileDown,
  Loader2,
  AlertCircle,
  RefreshCw,
  Eye,
  Clock,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useDeclaration, useUpdateDeclaration } from "@/hooks/use-declaration";
import type { DeclarationAnswers, AutoGeneratedStats, HubSubmittedAppResponse } from "@/lib/types";
import { DeclarationSummaryCards } from "./declaration-summary-cards";
import { DeclarationQuestionnaire } from "./declaration-questionnaire";
import { DeclarationPDFDocument } from "./declaration-pdf-document";

const DEFAULT_ANSWERS: DeclarationAnswers = {
  recruitmentMethod: "",
  recruitmentEase: "",
  testerEngagement: "",
  feedbackSummary: "",
  feedbackCollectionMethod: "",
  intendedAudience: "",
  valueDescription: "",
  expectedInstalls: "",
  changesMade: "",
  readinessRationale: "",
  customQuestions: [],
  deletedQuestions: [],
};

const DEFAULT_STATS: AutoGeneratedStats = {
  totalTesters: 0,
  completedTesters: 0,
  totalDays: 0,
  currentDay: 0,
  bugs: 0,
  suggestions: 0,
  praise: 0,
  totalFeedback: 0,
  totalRatings: 0,
  avgRating: null,
  appType: "FREE",
  hasCriticalBugs: false,
  testingStartDate: null,
  testingEndDate: null,
  packageName: "",
  category: "",
};

export function DeclarationReport({
  appId,
  appDetails,
  onClose,
}: {
  appId: string | number;
  appDetails?: HubSubmittedAppResponse;
  onClose?: () => void;
}) {
  const [activeTab, setActiveTab] = useState("summary");
  const [answers, setAnswers] = useState<DeclarationAnswers>(DEFAULT_ANSWERS);

  const { data: declaration, isPending, error, refetch } = useDeclaration(appId);
  const { mutateAsync: updateDeclaration } = useUpdateDeclaration();

  const stats: AutoGeneratedStats =
    declaration?.autoGeneratedData || DEFAULT_STATS;

  const adminQuestions = declaration?.adminAnswers?.questions;
  const isPaidApp = stats.appType === "PAID";

  useEffect(() => {
    if (declaration?.answers) {
      setAnswers({
        ...DEFAULT_ANSWERS,
        ...declaration.answers,
        customQuestions: declaration.answers.customQuestions || [],
        deletedQuestions: declaration.answers.deletedQuestions || [],
      });
    }
  }, [declaration]);

  const handleAnswersChange = useCallback(
    (newAnswers: DeclarationAnswers) => {
      setAnswers(newAnswers);
      updateDeclaration({ appId, answers: newAnswers }).catch(console.error);
    },
    [appId, updateDeclaration],
  );

  if (isPending) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error) {
    const isBeingPrepared = error.message?.toLowerCase().includes("being prepared");
    return (
      <div className="flex flex-col items-center justify-center py-20 gap-4">
        {isBeingPrepared ? (
          <>
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
              <Clock className="w-8 h-8 text-primary" />
            </div>
            <h3 className="text-xl font-bold">Report is Being Prepared</h3>
            <p className="text-muted-foreground text-center max-w-md">
              The declaration report for this app is currently being prepared by our team.
              Please check back later. You will be notified once it is available.
            </p>
          </>
        ) : (
          <>
            <AlertCircle className="w-12 h-12 text-destructive" />
            <p className="text-muted-foreground">
              {error.message || "Failed to load declaration"}
            </p>
          </>
        )}
        <Button variant="outline" onClick={() => refetch()}>
          <RefreshCw className="w-4 h-4 mr-2" />
          Retry
        </Button>
      </div>
    );
  }

  const appName = appDetails?.androidApp?.appName || stats.packageName || "App";
  const packageName = appDetails?.androidApp?.packageName || stats.packageName;
  const category = appDetails?.androidApp?.appCategory?.name || stats.category;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Declaration Report</h2>
          <p className="text-sm text-muted-foreground">
            Testing summary and Google Play production declaration
          </p>
        </div>
        <div className="flex items-center gap-2">
          {onClose && (
            <Button variant="outline" onClick={onClose} size="sm">
              Close
            </Button>
          )}
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="w-full sm:w-auto grid grid-cols-3 sm:inline-flex">
          <TabsTrigger value="summary" className="gap-2">
            <BarChart3 className="w-4 h-4" />
            <span className="hidden sm:inline">Summary</span>
          </TabsTrigger>
          <TabsTrigger value="questions" className="gap-2">
            <FileText className="w-4 h-4" />
            <span className="hidden sm:inline">Declaration</span>
          </TabsTrigger>
          <TabsTrigger value="download" className="gap-2">
            <FileDown className="w-4 h-4" />
            <span className="hidden sm:inline">Download PDF</span>
          </TabsTrigger>
        </TabsList>

        <div className="relative pt-6">
          <AnimatePresence mode="wait">
            {activeTab === "summary" && (
              <motion.div
                key="summary"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
              >
                <DeclarationSummaryCards stats={stats} />
              </motion.div>
            )}

            {activeTab === "questions" && (
              <motion.div
                key="questions"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
              >
                <DeclarationQuestionnaire
                  answers={answers}
                  onChange={handleAnswersChange}
                  adminQuestions={adminQuestions}
                />
              </motion.div>
            )}

            {activeTab === "download" && (
              <motion.div
                key="download"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
              >
                <div className="rounded-2xl bg-card p-8 max-w-2xl mx-auto text-center">
                  <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-6">
                    <FileDown className="w-8 h-8 text-primary" />
                  </div>
                  <h3 className="text-xl font-bold mb-2">Download PDF Report</h3>
                  <p className="text-sm text-muted-foreground mb-8 max-w-md mx-auto">
                    Download a complete PDF report containing all testing metrics and your
                    Google Play declaration answers. Use this as reference when submitting
                    your production access application.
                  </p>

                  <PDFDownloadLink
                    document={
                  <DeclarationPDFDocument
                      answers={answers}
                      stats={stats}
                      appName={appName}
                      packageName={packageName}
                      category={category}
                      deletedQuestions={answers.deletedQuestions}
                      adminQuestions={adminQuestions}
                    />
                    }
                    fileName={`${appName.replace(/\s+/g, "_")}_Testing_Report.pdf`}
                    className="inline-block"
                  >
                    {({ loading }: { loading: boolean }) => (
                      <Button
                        size="lg"
                        disabled={loading}
                        className="gap-3 min-w-[240px]"
                      >
                        {loading ? (
                          <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                            Generating PDF...
                          </>
                        ) : (
                          <>
                            <FileDown className="w-5 h-5" />
                            Download PDF Report
                          </>
                        )}
                      </Button>
                    )}
                  </PDFDownloadLink>

                  <div className="mt-8 text-left bg-muted/50 rounded-xl p-4 text-xs text-muted-foreground space-y-2">
                    <p className="flex items-center gap-2">
                      <Eye className="w-3.5 h-3.5" />
                      <strong>The PDF includes:</strong>
                    </p>
                    <ul className="list-disc pl-6 space-y-1">
                      <li>Cover page with app details and executive summary</li>
                      <li>Testing metrics dashboard (testers, feedback, ratings)</li>
                      {isPaidApp ? (
                        <li>Admin declaration questions &amp; answers (prepared by our team)</li>
                      ) : (
                        <li>All Google Play declaration questions with your answers</li>
                      )}
                      <li>Your custom questions and answers</li>
                      <li>Formatted for easy reference</li>
                    </ul>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </Tabs>
    </motion.div>
  );
}
